include: package:pedantic/analysis_options.yaml

analyzer:
  enable-experiment:
    - variance
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    import_of_legacy_library_into_null_safe: false


linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
