include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - variance
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false


linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
    non_constant_identifier_names: false
