include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - variance
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  errors:
    import_of_legacy_library_into_null_safe: ignore
    todo: ignore

linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
