name: reified_lenses_builder
version: 0.1.0
description: >-
  Code generation for reified lenses.
repository: https://gitlab.com/arrow/reified_lenses_builder
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  reified_lenses:
    path:
      ../reified_lenses
  build: '>=0.12.6 <2.0.0'
  source_gen: '>=0.9.0 <1.0.0'
  analyzer: ^0.39.4

dev_dependencies:
  build_runner:
  pedantic: ^1.9.0
  effective_dart: ^1.2.1
