name: reified_lenses_builder
version: 0.1.0
description: >-
  Code generation for reified lenses.
publish_to: none

environment:
  sdk: ">=2.15.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0-nullsafety.6
  reified_lenses:
    path:
      ../reified_lenses
  flutter_reified_lenses:
    path:
      ../flutter_reified_lenses
  build: ^2.0.1
  source_gen: ^1.0.0
  analyzer: ^4.5.0

dev_dependencies:
  build_runner: ^2.0.1
  flutter_lints: ^2.0.1
  effective_dart: ^1.2.1
