name: flutter_reified_lenses
version: 0.1.0
description: >-
  Flutter extensions for the reified_lenses library.
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  reified_lenses:
    path: ../reified_lenses
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  ctx:
    path: ../ctx

dev_dependencies:
  flutter_lints: ^2.0.1
  reified_lenses_builder:
    path: ../reified_lenses_builder
  build_runner: ^2.0.1
