name: flutter_reified_lenses
version: 0.1.0
description: >-
  Flutter extensions for the reified_lenses library.
repository: https://gitlab.com/arrow/flutter_reified_lenses
publish_to: none

environment:
  sdk: ">=2.15.0-0 <3.0.0"

dependencies:
  reified_lenses:
    path: ../reified_lenses
  flutter:
    sdk: flutter
  flutter_hooks:
    path: ../flutter_hooks/packages/flutter_hooks
  ctx:
    path: ../ctx

dev_dependencies:
  flutter_lints: ^1.0.4
  reified_lenses_builder:
    path:
      ../reified_lenses_builder
  build_runner: ^2.0.1
