name: functional
version: 0.1.0
description: >-
  Things I'm used to from functional programming, but Dart-like.
repository: https://gitlab.com/arrow/functional
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0-nullsafety.6
  reified_lenses:
    path:
      ../reified_lenses

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test:
  reified_lenses_builder:
    path:
      ../reified_lenses_builder
  build_runner: ^1.10.7
