name: reified_lenses
version: 0.1.0
description: >-
  Highly opinionated granular reactive state management for immutable state objects. (Words!)
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta:
  ctx:
    path:
      ../ctx

dev_dependencies:
  reified_lenses_builder:
    path: ../reified_lenses_builder
  build_runner: 
  lints: ^2.0.0
  test: 
