name: reified_lenses
version: 0.1.0
description: >-
  Highly opinionated granular reactive state management for immutable state objects. (Words!)
publish_to: none

environment:
  sdk: ">=2.13.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  ctx:
    path:
      ../ctx

dev_dependencies:
  reified_lenses_builder:
    path:
      ../reified_lenses_builder
  build_runner: ^2.1.1
  lints: ^1.0.1
  test: ^1.19.5
